# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApisAsana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'apis_asana',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApisSlack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'apis_slack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApisTeamviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'apis_teamviewer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('calificacionesid', models.AutoField(primary_key=True, serialize=False)),
                ('calificacionesnombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'calificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('clientesid', models.AutoField(primary_key=True, serialize=False)),
                ('clienteslogin', models.CharField(blank=True, max_length=50, null=True)),
                ('clientespass', models.CharField(blank=True, max_length=50, null=True)),
                ('clientesnombre', models.CharField(blank=True, max_length=50, null=True)),
                ('clientescorreo', models.CharField(blank=True, max_length=30, null=True)),
                ('clientestelefono', models.CharField(blank=True, max_length=30, null=True)),
                ('clientesrfc', models.CharField(blank=True, max_length=13, null=True)),
                ('clientesnacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('cotizacionid', models.AutoField(primary_key=True, serialize=False)),
                ('cotizacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cotizaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccionclientes',
            fields=[
                ('direccionclientesid', models.AutoField(primary_key=True, serialize=False)),
                ('calles', models.CharField(blank=True, max_length=60, null=True)),
                ('numerointerior', models.CharField(blank=True, max_length=10, null=True)),
                ('numeroexterior', models.CharField(blank=True, max_length=10, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=30, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('pais', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'direccionclientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccionespecialistas',
            fields=[
                ('direccionespecialistasid', models.AutoField(primary_key=True, serialize=False)),
                ('calles', models.CharField(blank=True, max_length=60, null=True)),
                ('numerointerior', models.CharField(blank=True, max_length=10, null=True)),
                ('numeroexterior', models.CharField(blank=True, max_length=10, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=30, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('pais', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'direccionespecialistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSlackOauthSlackoauthrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=128, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_slack_oauth_slackoauthrequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField()),
                ('download_url', models.CharField(max_length=1024)),
                ('host', models.CharField(max_length=24)),
                ('permanent_url', models.CharField(max_length=1024)),
                ('view_url', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'djasana_attachment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('archived', models.BooleanField()),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField()),
                ('current_status', models.CharField(blank=True, max_length=16, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('layout', models.CharField(max_length=16)),
                ('modified_at', models.DateTimeField()),
                ('notes', models.TextField()),
                ('public', models.BooleanField()),
            ],
            options={
                'db_table': 'djasana_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaProjectFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'djasana_project_followers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaProjectMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'djasana_project_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('hearted', models.BooleanField()),
                ('num_hearts', models.SmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('target', models.BigIntegerField()),
                ('source', models.CharField(max_length=16)),
                ('text', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'djasana_story',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaStoryHearts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'djasana_story_hearts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaSynctoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'djasana_synctoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'djasana_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('hearted', models.BooleanField()),
                ('num_hearts', models.SmallIntegerField()),
                ('assignee_status', models.CharField(max_length=16)),
                ('completed', models.BooleanField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('modified_at', models.DateTimeField()),
                ('notes', models.TextField()),
            ],
            options={
                'db_table': 'djasana_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaTaskFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'djasana_task_followers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaTaskHearts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'djasana_task_hearts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaTaskProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'djasana_task_projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaTaskTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'djasana_task_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('organization_id', models.BigIntegerField(blank=True, null=True)),
                ('organization_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'djasana_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=254)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'djasana_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaUserWorkspaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'djasana_user_workspaces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'djasana_webhook',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjasanaWorkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('is_organization', models.BooleanField()),
            ],
            options={
                'db_table': 'djasana_workspace',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialistas',
            fields=[
                ('especialistasid', models.AutoField(primary_key=True, serialize=False)),
                ('especialistaslogin', models.CharField(blank=True, max_length=50, null=True)),
                ('especialistaspass', models.CharField(blank=True, max_length=50, null=True)),
                ('especialistasnombre', models.CharField(blank=True, max_length=50, null=True)),
                ('especialistasnacimiento', models.DateField(blank=True, null=True)),
                ('especialistastelefono', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'especialistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('etapasid', models.AutoField(primary_key=True, serialize=False)),
                ('etapasnombre', models.CharField(blank=True, max_length=40, null=True)),
                ('etapasduracion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'etapas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('experienciaid', models.AutoField(primary_key=True, serialize=False)),
                ('experienciarango', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'experiencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('gradosid', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'grados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('nivelesid', models.AutoField(primary_key=True, serialize=False)),
                ('nivelnombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'niveles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesiones',
            fields=[
                ('profesionesid', models.AutoField(primary_key=True, serialize=False)),
                ('profesion', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'profesiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('proyectoid', models.AutoField(primary_key=True, serialize=False)),
                ('proyectonombre', models.CharField(blank=True, max_length=40, null=True)),
                ('proyectodescripcions', models.CharField(blank=True, max_length=150, null=True)),
                ('proyectoduracion', models.IntegerField(blank=True, null=True)),
                ('proyectoinicio', models.DateField(blank=True, null=True)),
                ('proyectofinal', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rolid', models.AutoField(primary_key=True, serialize=False)),
                ('roldescripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('serviciosid', models.AutoField(primary_key=True, serialize=False)),
                ('serviciosnombre', models.CharField(blank=True, max_length=50, null=True)),
                ('serviciosdescripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusid', models.AutoField(primary_key=True, serialize=False)),
                ('statusnombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statusproyecto',
            fields=[
                ('statusproyectoid', models.AutoField(primary_key=True, serialize=False)),
                ('statusproyecto', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'statusproyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('tareasid', models.AutoField(primary_key=True, serialize=False)),
                ('tareasnombre', models.CharField(blank=True, max_length=40, null=True)),
                ('tareasduracion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocliente',
            fields=[
                ('tipoclienteid', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipocliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Juan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Etapastareas',
            fields=[
                ('etapastareasid', models.OneToOneField(db_column='etapastareasid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='apis.Etapas')),
            ],
            options={
                'db_table': 'etapastareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyectodescripcion',
            fields=[
                ('proyectoid', models.OneToOneField(db_column='proyectoid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='apis.Proyectos')),
            ],
            options={
                'db_table': 'proyectodescripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('slacker', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='apis.AuthUser')),
                ('access_token', models.CharField(blank=True, max_length=128, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'slack_user',
                'managed': False,
            },
        ),
    ]
